# Generated by Django 3.2.5 on 2022-05-15 01:50

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
